-- models/calendar_model.sql

SELECT
  "date" AS date,
  "day_of_week" AS day_of_week,
  "month" AS month,
  "quarter" AS quarter,
  "year" AS year,
  "day_number_of_week" AS day_number_of_week,
  "week_number_of_month" AS week_number_of_month,
  "week_number_of_quarter" AS week_number_of_quarter,
  "week_number_of_year" AS week_number_of_year,
  "is_weekend" AS is_weekend,
  "monthly" AS monthly,
  "quarterly" AS quarterly,
  "day_number_of_month" AS day_number_of_month,
  "day_number_of_quarter" AS day_number_of_quarter,
  "day_number_of_year" AS day_number_of_year,
  "month_number_of_quarter" AS month_number_of_quarter,
  "month_number_of_year" AS month_number_of_year,
  "quarter_number_of_year" AS quarter_number_of_year,
  "absolute_week_number" AS absolute_week_number,
  "start_of_week_epoch" AS start_of_week_epoch,
  "end_of_week_epoch" AS end_of_week_epoch,
  "absolute_month_number" AS absolute_month_number,
  "start_of_month_epoch" AS start_of_month_epoch,
  "end_of_month_epoch" AS end_of_month_epoch,
  "absolute_quarter_number" AS absolute_quarter_number,
  "start_of_quarter_epoch" AS start_of_quarter_epoch,
  "end_of_quarter_epoch" AS end_of_quarter_epoch,
  "absolute_year_number" AS absolute_year_number,
  "start_of_year_epoch" AS start_of_year_epoch,
  "end_of_year_epoch" AS end_of_year_epoch
FROM "DEVELOPMENT"."TS_dataset"."CCRonyTable"
